[package]
name = "numtracker"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lints.clippy]
unwrap_used = "deny"

[dependencies]
async-graphql = { version = "7.0.11", features = ["tracing"] }
async-graphql-axum = "7.0.11"
axum = "0.7.5"
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["cargo", "derive", "env"] }
futures = "0.3.30"
opentelemetry = "0.24.0"
opentelemetry-otlp = "0.17.0"
opentelemetry-semantic-conventions = "0.16.0"
opentelemetry-stdout = "0.5.0"
opentelemetry_sdk = { version = "0.24.1", features = ["rt-tokio"] }
sqlx = { version = "0.8.0", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.25.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.2"

[dev-dependencies]
async-std = { version = "1.13.0", features = ["attributes"], default-features = false }
rstest = "0.23.0"
